image: debian:11
stages:
  - build
  - aptrepo

variables:
  APT_REPO: imedia-hpbx-testing
  DEB_ARCH: amd64
  DEVEMAIL: dgirdyuk@intermedia.net
  DEB_USER: jenkins
  DEB_GROUP: jenkins
  PYTHON_BINARY: python3

.debain11-defaults:
  image: debian:11
  variables:
    DEB_OS_PREFIX: deb11
    DISTR: bullseye
    APT_LOCAL_REPO: imedia-hpbx-testing-${DISTR}
    APT_DIR: imedia-hpbx-testing-${DISTR}
    PYTHON_BINARY: python3.9

.hpbx-smoke-tests-default:build:
  stage: build
  tags: [hpbx]
  before_script:
    - apt-get update
    - apt-get install git curl gnupg2 ruby ruby-dev rubygems build-essential -y
  after_script:
    - ./makeall.sh
  artifacts:
    expire_in: 1 days
    paths:
      - "*deb" 

.hpbx-smoke-tests-default:aptrepo:
  stage: aptrepo
  tags: [hpbx]
  script:
    - apt-get update
    - apt-get install curl -y
    - ./pushdeb.sh


hpbx-smoke-tests-deb11:build:
  extends: 
    - .debain11-defaults
    - .hpbx-smoke-tests-default:build
  script:
    - gem install --no-document fpm -v 1.14.0

hpbx-smoke-tests-deb11:aptrepo:
  extends: 
    - .debain11-defaults
    - .hpbx-smoke-tests-default:aptrepo
