################################################################################
### Common
################################################################################

version: 1

################################################################################
### Formatters
################################################################################

formatters:
    simpleFormater:
        format: '%(asctime)s | %(levelname)-8s | %(name)-30s | %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

################################################################################
### Handlers
################################################################################

handlers:
    file:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug.log

    file_reactor:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_reactor.log

    file_blf:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_blf.log

    file_sip:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_sip.log

    file_pbxut_util:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_pbxut_util.log

    file_pbxut:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_pbxut.log

    file_cp:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_cp.log

    file_testlink:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_testlink.log

    file_callflow:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_callflow.log

    file_inspector:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_inspector.log

    file_hpbxdm:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_hpbxdm.log

    file_db:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_db.log

    file_audio:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_audio.log

    file_mail:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_mail.log

    file_umsctlclient:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_umsctlclient.log

    file_rmqclient:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: debug_rmqclient.log


################################################################################
### Loggers
################################################################################
loggers:

    # System "requests" and etc.
    requests:
        level: INFO
        handlers: []
        propagate: 0

    urllib3:
        level: INFO
        handlers: []
        propagate: 0

    # Work with "SIP" and etc.
    sipde:
        level: DEBUG
        handlers: [file_sip]
        propagate: 0

    sipre:
        level: DEBUG
        handlers: [file_sip]
        propagate: 0

    sipne:
        level: DEBUG
        handlers: [file_blf]
        propagate: 0

    siplib:
        level: DEBUG
        handlers: [file_blf]
        propagate: 0

    reactor:
      level: DEBUG
      handlers: [file_reactor]
      propagate: 0

    blf_client_factory:
      level: DEBUG
      handlers: [file_callflow]
      propagate: 0

    basecallfuncs:
      level: DEBUG
      handlers: [file_callflow]
      propagate: 0

    call_functions:
        level: DEBUG
        handlers: [file_callflow]
        propagate: 0

    client_factory:
        level: DEBUG
        handlers: [file_callflow]
        propagate: 0

    af:
        level: DEBUG
        handlers: [file_audio]
        propagate: 0

    waveproc:
        level: DEBUG
        handlers: [file_audio]
        propagate: 0

    step_manager:
      level: INFO
      handlers: [file_callflow]
      propagate: 0

    unison_cp_client:
        level: DEBUG
        handlers: [file_cp]
        propagate: 0

    hpbx_dm:
        level: DEBUG
        handlers: [file_hpbxdm]
        propagate: 0

    hpbx_base:
        level: DEBUG
        handlers: [file_db]
        propagate: 0

    pbxut:
        level: DEBUG
        handlers: [file_pbxut]
        propagate: 0

    pbxut_util:
        level: DEBUG
        handlers: [file_pbxut_util]
        propagate: 0

    testlink:
        level: DEBUG
        handlers: [file_testlink]
        propagate: 0

    runtime_inspector:
        level: DEBUG
        handlers: [file_inspector]
        propagate: 0

    mailbox_functions:
        level: DEBUG
        handlers: [file_mail]
        propagate: 0

    mcc:
        level: DEBUG
        handlers: [file_mail]
        propagate: 0
        
    case:
        level: DEBUG
        handlers: [file_callflow]
        propagate: 0

    umsctlclient:
        level: DEBUG
        handlers: [file_umsctlclient]
        propagate: 0

    rmqclient:
        level: DEBUG
        handlers: [file_rmqclient]
        propagate: 0

    pika:
        level: INFO
        handlers: [file_rmqclient]
        propagate: 0

    context:
        level: DEBUG
        handlers: [file]
        propagate: 0

################################################################################
### ROOT
################################################################################

root:
    level: DEBUG
    handlers: [file]
